/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Dao.UserDao;
import Logica.View;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Director
 */
public class RecoverPasswordInterface extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RecoverPasswordInterface() {
        initComponents();
        this.setTitle("LES");
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/LESlogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSerial1 = new javax.swing.JLabel();
        jButtonComfirmar1 = new javax.swing.JButton();
        jButtonBack1 = new javax.swing.JButton();
        textLogin1 = new javax.swing.JLabel();
        IconAccount1 = new javax.swing.JLabel();
        iconUser1 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSerial1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSerial1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSerial1.setText("IDENTIFICACION");
        getContentPane().add(jLabelSerial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jButtonComfirmar1.setBackground(new java.awt.Color(127, 0, 0));
        jButtonComfirmar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonComfirmar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComfirmar1.setText("Confrimar");
        jButtonComfirmar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonComfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComfirmar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jButtonBack1.setBackground(new java.awt.Color(127, 0, 0));
        jButtonBack1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack1.setText("Volver");
        jButtonBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, -1));

        textLogin1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textLogin1.setForeground(new java.awt.Color(102, 102, 102));
        textLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogin1.setText("RESTABLECER CONTRASEÑA");
        getContentPane().add(textLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 303, 28));

        IconAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accounts.png"))); // NOI18N
        getContentPane().add(IconAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        iconUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LESlogo.png"))); // NOI18N
        getContentPane().add(iconUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 135));

        jTextFieldIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel4");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonComfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComfirmar1ActionPerformed
       UserDao objDao = new UserDao();
       View objView = new View();
       String question=objDao.getQuestion(jTextFieldIdentificacion.getText());
       String answer = objView.valitadionAnswer(question);
       if(answer.equals(objDao.getAnswer(jTextFieldIdentificacion.getText()))){
           System.out.println(objDao.getAnswer(jTextFieldIdentificacion.getText())); 
           objView.sucessfulOperationTypeElement("Contraseña","restaurada");
           InitialInterface objWindow = new InitialInterface();
           objWindow.generateInitialPassword();
       }
       
    }//GEN-LAST:event_jButtonComfirmar1ActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        LoginInterface objVentana = new LoginInterface();
        objVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPasswordInterface().setVisible(true);
            }
        });
    }
  
  public void showQuestion(){
  
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconAccount1;
    private javax.swing.JLabel iconUser1;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonComfirmar1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSerial1;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JLabel textLogin1;
    // End of variables declaration//GEN-END:variables

}
