/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Dao.UserDao;
import Logica.Validate;
import Logica.View;
import javax.swing.ImageIcon;

/**
 *
 * @author Director
 */
public class RecoverPasswordInterface extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RecoverPasswordInterface() {
        initComponents();
        this.setTitle("LES");
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/LESlogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIdTitle = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        textTitle = new javax.swing.JLabel();
        IconAccount1 = new javax.swing.JLabel();
        iconLES = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIdTitle.setText("IDENTIFICACION");
        getContentPane().add(jLabelIdTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jButtonConfirmar.setBackground(new java.awt.Color(127, 0, 0));
        jButtonConfirmar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 30));

        jButtonBack.setBackground(new java.awt.Color(127, 0, 0));
        jButtonBack.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Volver");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, 30));

        textTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textTitle.setForeground(new java.awt.Color(102, 102, 102));
        textTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitle.setText("RESTABLECER CONTRASEÑA");
        getContentPane().add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 303, 28));

        IconAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accounts.png"))); // NOI18N
        getContentPane().add(IconAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        iconLES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LESlogo.png"))); // NOI18N
        getContentPane().add(iconLES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 135));

        jTextFieldIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        jTextFieldIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdentificacionKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel4");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
     
       UserDao objDao = new UserDao();
       View objView = new View();
       
       String identification = jTextFieldIdentificacion.getText();
       String question=objDao.getData(identification , "SELECT secret_question FROM users WHERE identification='" ,"secret_question" );
       String validateAnswer = objView.valitadionAnswer(question);
       String answer = objDao.getData(identification , "SELECT secret_answer FROM users WHERE identification='" ,"secret_answer");
       if(validateAnswer.equals(answer)){
           
          String password = generatePassword();
          boolean cheek =objDao.updatePassword(identification, password);
          if(cheek== true){
               View message = new View();
               message.sucessfulOperationTypeElement("Su contreseña", "generada");
          }
          
       }
       
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        LoginInterface objVentana = new LoginInterface();
        objVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionKeyTyped
        Validate field = new Validate();
        field.numericFieldValidation(jTextFieldIdentificacion);
    }//GEN-LAST:event_jTextFieldIdentificacionKeyTyped

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacionActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPasswordInterface().setVisible(true);
            }
        });
    }
  
  public String  generatePassword(){
           
           UserDao objDao = new UserDao();
           String identification = jTextFieldIdentificacion.getText();
           String name = objDao.getData(identification , "SELECT name FROM users WHERE identification='" ,"name");           
           String initial = name.substring(0, 1);
           char last = name.charAt(name.length() - 1);
           String password = (initial + identification + last).toUpperCase();
           return password;
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconAccount1;
    private javax.swing.JLabel iconLES;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIdTitle;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JLabel textTitle;
    // End of variables declaration//GEN-END:variables

}
